### PR TITLE
Land one view csv more columns

### PR DESCRIPTION
**Pull request by stevenjowens**
Revised the columns in the CSV so that the CSV includes all columns displayed on the page, in the order they occur on the page.  

Kept existing CSV column headers where they differed in name from the page column headers.

### CODE REVIEW

**Comment by pennsicwar** [comment]
You need to fix column M, the change percentage. It's coming thru as "-&nbsp;99&nbsp;%"

**Comment by stevenjowens** [comment]
I'm not seeing that on the CSV downloaded from
https://land-test-rhys.pennsicwar.net/TEST/admin_land_one.php, it's
coming through as "(new)" or in one case (+0%).  See attached.


On Tue, Jan 14, 2020 at 6:01 PM pennsicwar <notifications@github.com> wrote:
>
> You need to fix column M, the change percentage. It's coming thru as "- 99 %"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Steven J. Owens
stevenjowens@gmail.com
puff@darksleep.com
412-401-8060

**Comment by stevenjowens** [comment]
Also, literally all I did was add the $change_percent variable to the
list of variables to be written.

I don't see anything extra in the code to convert $change_percent
before displaying it in the HTML, so what's going into the CSV should
be exactly the same as what's in the UI.

Steve

On Tue, Jan 14, 2020 at 10:37 PM Steven Owens <stevenjowens@gmail.com> wrote:
>
> I'm not seeing that on the CSV downloaded from
> https://land-test-rhys.pennsicwar.net/TEST/admin_land_one.php, it's
> coming through as "(new)" or in one case (+0%).  See attached.
>
>
> On Tue, Jan 14, 2020 at 6:01 PM pennsicwar <notifications@github.com> wrote:
> >
> > You need to fix column M, the change percentage. It's coming thru as "- 99 %"
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
>
>
>
> --
> Steven J. Owens
> stevenjowens@gmail.com
> puff@darksleep.com
> 412-401-8060



-- 
Steven J. Owens
stevenjowens@gmail.com
puff@darksleep.com
412-401-8060

**Comment by pennsicwar** [comment]
Right, and $change_percent contains a string of html entities.  What's more concerning to me tho is that you aren't getting
`
ChangePercent
--
-&nbsp;100&nbsp;%
-&nbsp;90&nbsp;%
-&nbsp;99&nbsp;%
-&nbsp;100&nbsp;%
-&nbsp;100&nbsp;%
-&nbsp;100&nbsp;%
-&nbsp;100&nbsp;%
`
and it's totally being wrappered here:

`115:      $change_percent_sortkey = $change_percent;
116:      $change_percent = ( ($change_percent < 0) ? ("-&nbsp;") : ("+&nbsp;") )
`

However, I can just put $change_percent_sortkey in the output file and it should work fine.  I'll pull this change and then just throw that one touchup on top of it.

**Pull request merged**
